### ISSUE TITLE
I'm not sure this is working in 1.7.0

### ISSUE THREAD

**Issue by blakejrobinson** [SenshiSentou/sd-webui-state-manager#1] opened 2023-12-18 15:18 UTC
Sounds like this will be really useful but I can't seem to get it to work. I noticed a few things trying this out:

- "Auto-save" seems to be disabled by default which doesn't match documentation,
- With Auto-save on, nothing seems to save,
- Saving manually puts an item into 'Favourites', this disappears when hitting F5. There seem to be no History or Favourites on page refresh,
- The manually saved items seem to have no thumbnail: ![image](https://github.com/SenshiSentou/sd-webui-state-manager/assets/9593019/f5797efa-372d-4719-b112-c2f9e03d0535)

My install details:

- Windows 10 (latest)
- Version: [v1.7.0]
- Python: 3.10.9 (with webui created venv)
- Torch: 2.0.1+cu118  
- Xformers: N/A  
- Gradio: 3.41.2  
- Tried with Gradio auth on and off
- Checkpoint: [71e14760e2]

**Comment by ryanull24** [comment] 2023-12-18 17:40
I m also having issues with it - I can t get it to work. I can see the save / load buttons whatever, but the UI seems broken, all white, unreadable text, but I got it to save something (no items checkmark like author shows) which was gone after a reload

**Comment by SenshiSentou** [comment] 2023-12-19 17:16
That's odd, it was tested in master just last week. I can check later this week. In the meantime, do either of you have any related console outputs?

**Comment by ryanull24** [comment] 2023-12-19 17:47
I can't see any output in the console. I do have a bunch of other extensions, so there may be a conflict?

If I save my settings, under Favorites > double click a saved one I can see it changing at least the prompt.

![image](https://github.com/SenshiSentou/sd-webui-state-manager/assets/92233600/b827943f-16b5-4b97-a1a0-3f3a938fd8cf)

Regular, non-extended panel looks like this:

![image](https://github.com/SenshiSentou/sd-webui-state-manager/assets/92233600/5883a83a-29c9-4008-99fe-83c53ed69abf)




version: [v1.7.0]  •  python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2


L.E. Installed a fresh version of a1111 1.7.0 to test this, switched to white theme; now text is readable, but still the same issues as above

Later L.E. I don't know if this might be of any use:

![image](https://github.com/SenshiSentou/sd-webui-state-manager/assets/92233600/3b37af29-c0a8-4291-a565-fa3f0510d608)

**Comment by Antivash** [comment] 2023-12-22 20:12
Getting similar results out of pretty much every browser I try; Opera GX, Brave, Edge, Chrome.  Thought setting log level to debug might help, but no new information in the console window. Everything loads fine, I can favorite things, but everything vanishes when I restart.


![image](https://github.com/SenshiSentou/sd-webui-state-manager/assets/336178/5db888fb-86d9-4dfc-9f46-e0b635eeef0e)

**Comment by vis223** [comment] 2023-12-23 17:32
I hope you can figure this all out as it looks to be something that is really needed. 
I can confirm similar UI issues in SD Next but I guess there's much to fix in A1111 first. 
Keep up the good work. This definitely has huge potential.

**Comment by PeanutButterSkeletonCrew** [comment] 2024-01-08 09:33
I have the same issues with 1.7.0. Hope this get resolved, this extension is exactly what I've wanted for a long time. It has lots of potential.

**Comment by CHollman82** [comment] 2024-01-15 13:50
Same issue here, I saved a few things, put them in favorites, then lost them. Seems like whenever you reload the page in your browser or close and reopen it everything that you thought was saved is gone.

**Comment by SenshiSentou** [comment] 2024-01-16 00:31
I'm spending some time working on this this week. I just pulled to the latest 1.7.0 and everything still works as expected for me, on both FF and Chrome. To the people having issues: Are you on the latest(ish) browser versions?

**Comment by CHollman82** [comment] 2024-01-16 05:48
I'm using this Chrome version: 120.0.6099.200 (Official Build) (64-bit)

**Comment by PeanutButterSkeletonCrew** [comment] 2024-01-16 10:33
I'm using Chrome Version 120.0.6099.217 (Official Build) (64-bit)

**Comment by SenshiSentou** [comment] 2024-01-16 11:43
Thanks both. I just pushed a commit that I think should fix the issue. Can you let me know if it works?

**Comment by PeanutButterSkeletonCrew** [comment] 2024-01-17 12:44
Thanks for the commit. I tested it and it does seem to work! Saved UIs and history seem to persist across sessions and double-clickling them loads the saved state. Thanks for fixing this! (EDIT: See my next comment for an update on this).

The only issue I'm having now is that my system uses dark mode and the state manager UI doesn't display many elements properly when in dark mode. I can work around that but it'd be great to see a fix if you get an opportunity :)

EDIT: I should say that the UI doesn't seem to show any of the config settings that are shown in the github screenshots, even when in light mode.

**Comment by PeanutButterSkeletonCrew** [comment] 2024-01-17 13:02
I did some more testing and while the basic settings (prompt etc) seem to be saved / loaded, settings for extensions (e.g. ControlNet, AfterDetailer) don't seem to load. I'm not sure if they're supposed to or not, it'd be great if they could though, it would save me a lot of time every time I load up A111.

**Comment by SenshiSentou** [comment] 2024-01-17 23:53
Extension settings are absolutely meant to be saved as well. Could you show me a screenshot of what things look like on your end? I'll take a second look at dark mode for sure, but I'm especially interested in the elements that are always missing

**Comment by PeanutButterSkeletonCrew** [comment] 2024-01-18 10:09
Unfortunately it seems the saved states don't survive between system reboots. Weirdly, if I close and reopen A111 I see the saved states but after a reboot they vanish. I tried this several times to be certain. Perhaps they're persisting in memory but not being properly saved? If you can add some debug output around the save / load process I'd be happy to test again and send you the output.

Also, I've attached a snip of the extension in dark theme so you can see what's missing. Perhaps this is unrelated to dark theme and is just an extension of the save / load issue?

![window](https://github.com/SenshiSentou/sd-webui-state-manager/assets/155959949/ef6bd772-e7fd-4884-977b-54b01bea47a2)

**Comment by PeanutButterSkeletonCrew** [comment] 2024-01-18 10:38
I did some more detective work and have an update to my previous post! At least part of the problem seems to be caused by Incognito Mode in Chrome. I use A111 in Incognito by default. When in incognito mode I get the issue I described above (saved states not persisting after rebooting my PC). However if I'm in standard Chrome, this issue does not occur. I can save and reload states between reboots.

However, even in standard chrome it doesn't seem to save / restore settings for extensions (ControlNet etc) and it still misses all the information in the side panel as shown in my screenshot above. The only difference is that saved states persist between reboots.

I hope that's useful information for you in diagnosing the problem.

**Comment by ryanull24** [comment] 2024-01-29 12:16
> The only issue I'm having now is that my system uses dark mode and the state manager UI doesn't display many elements properly when in dark mode. I can work around that but it'd be great to see a fix if you get an opportunity :)
> 
> EDIT: I should say that the UI doesn't seem to show any of the config settings that are shown in the github screenshots, even when in light mode.

Same over here, and it seems i cannot delete saved states, but otherwise it works.

**Comment by SenshiSentou** [comment] 2024-02-24 00:29
I just did a huge rewrite on this addon. For those that were having issues, could you please try the $v2.0-beta branch? It's not 100% feature-complete yet, and **it will overwrite your current history**, but I'm curious if it at least display correctly now.

If you're getting errors, please manually clear all state-manager data from your localstorage's `ldb`
<img width="1728" alt="Screenshot 2024-02-24 at 01 28 17" src="https://github.com/SenshiSentou/sd-webui-state-manager/assets/4528688/bf063d11-44f4-4786-85f2-c88a9ff2740a">

**Comment by CHollman82** [comment] 2024-02-24 01:25
Thank you, I'll give it a try tomorrow. It's a great idea and a very useful
feature, thanks for developing it.

**Comment by Antivash** [comment] 2024-02-26 11:18
> I just did a huge rewrite on this addon. For those that were having issues, could you please try the $v2.0-beta branch? It's not 100% feature-complete yet, and **it will overwrite your current history**, but I'm curious if it at least display correctly now.
> 
> If you're getting errors, please manually clear all state-manager data from your localstorage's `ldb` <img alt="Screenshot 2024-02-24 at 01 28 17" width="1728" src="https://private-user-images.githubusercontent.com/4528688/307480251-bf063d11-44f4-4786-85f2-c88a9ff2740a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDUxNTQsIm5iZiI6MTcwODk0NDg1NCwicGF0aCI6Ii80NTI4Njg4LzMwNzQ4MDI1MS1iZjA2M2QxMS00NGY0LTQ3ODYtODVmMi1jODhhOWZmMjc0MGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjZUMTA1NDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ViNjQ2ZjYyOWRjZjIyYjNiZmVlMzk3NmNkZjI4ZjY0YTQyNGI2ZmZiZDBlOTQ4MWU1YjQyMTc5NWUyYjI1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zHAyoAHgKnFXjeuvy8Y8Yw8tmg74Tm6xj0yMMJAyIv0">

So with this one, I am getting an error with the v2.0-beta branch even after clearing. [Screenshot here](https://i.imgur.com/jP4Qgyu.png)

Changing line 64 of api.py from
```
with open(filepath,"r") as f:
```
to
```
with open(filepath,"r",encoding='utf-8') as f:
```

resolves the issue entirely for me. [Screenshot here](https://i.imgur.com/Hc9fUvY.png)

Im not sure if its just an issue with my setup in particular specifically, but once that change is made, it functions perfectly for me, so I figure I'd drop this here, just in case..

**Comment by SenshiSentou** [comment] 2024-02-26 20:32
@Antivash Great catch, thank you! Added this in

**Comment by PeanutButterSkeletonCrew** [comment] 2024-02-29 09:58
@SenshiSentou V2.0 mostly works! Thanks for the hard work! A few small issues I did notice with saving settings from specific extensions:

1.  ControlNet - If the user has multiple ControlNet units, only the settings for the first ControlNet unit are saved / restored
2. µ Detection Detailer - The state of the main checkbox for enabling the extension is not saved / restored. The Inpainting Options submenu doesn't seem to save manually entered values in the Inpainting Height / Width fields. I suspect the radio buttons for the size presets here are being applied over the manually entered values when the state is loaded.

Also the pop-out menu isn't legible in dark mode.

Other than that, everything works great! Thanks again for fixing the major issues :)

**Comment by PeanutButterSkeletonCrew** [comment] 2024-02-29 18:50
I did a bit more testing and it seems like my earlier flagged issue of saves not persisting between rebooting my system in incognito mode is still in V2.0. Hopefully you can find a fix that issue :)

**Comment by blakejrobinson** [comment] 2024-02-29 19:56
> I did a bit more testing and it seems like my earlier flagged issue of saves not persisting between rebooting my system in incognito mode is still in V2.0. Hopefully you can find a fix that issue :)

Isn't this the point of Incognito mode? It won't save sessions/history/etc.

**Comment by blakejrobinson** [comment] 2024-02-29 20:01
Gave the new version a try and definitely an improvement. I can't seem to get things like ControlNet to recall though (they seem to store okay, but it won't change any settings on 'Load generation settings' or 'Load all'

**Comment by ryanull24** [comment] 2024-03-05 11:36
> I just did a huge rewrite on this addon. For those that were having issues, could you please try the $v2.0-beta branch? It's not 100% feature-complete yet, and **it will overwrite your current history**, but I'm curious if it at least display correctly now.
> 
> If you're getting errors, please manually clear all state-manager data from your localstorage's `ldb` <img alt="Screenshot 2024-02-24 at 01 28 17" width="1728" src="https://private-user-images.githubusercontent.com/4528688/307480251-bf063d11-44f4-4786-85f2-c88a9ff2740a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzgzMjMsIm5iZiI6MTcwOTYzODAyMywicGF0aCI6Ii80NTI4Njg4LzMwNzQ4MDI1MS1iZjA2M2QxMS00NGY0LTQ3ODYtODVmMi1jODhhOWZmMjc0MGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMTEyNzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjk5MjIwYmVlNzNlNDJjMDgxNWU2YTIwYTgxYzAxZjhkMDg1NDM4MTk4ZWQ0ZTgzODNmZTdjNmI0ZjU4ZWYxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0XS-m0y_I8QOaghaZLuIpmStkGhKH5ZvTeybxS85UfY">

On my regular install it throws some errors and sd doesn't generate anything, on the fresh install that I tried the 1.0 extension (A111 1.7.0 still) same thing, but on a fresh Forge (A1111 fork) install **seems to work well**, so that's a me issue.

One little thing that annoys me is that the full screen mode is white when I am using dark mode, but other than that, all good.

**Comment by SenshiSentou** [comment] 2024-03-07 16:23
> @SenshiSentou V2.0 mostly works! Thanks for the hard work! A few small issues I did notice with saving settings from specific extensions:
> 
>     1. ControlNet - If the user has multiple ControlNet units, only the settings for the first ControlNet unit are saved / restored
> 
>     2. µ Detection Detailer - The state of the main checkbox for enabling the extension is not saved / restored. The Inpainting Options submenu doesn't seem to save manually entered values in the Inpainting Height / Width fields. I suspect the radio buttons for the size presets here are being applied over the manually entered values when the state is loaded.
> 
> 
> Also the pop-out menu isn't legible in dark mode.
> 
> Other than that, everything works great! Thanks again for fixing the major issues :)


> Gave the new version a try and definitely an improvement. I can't seem to get things like ControlNet to recall though (they seem to store okay, but it won't change any settings on 'Load generation settings' or 'Load all'

Dangit. ControlNet is always gonna be a bit of a PITA, with some of its state being control images and such. This is an unexpected one though, so I'll have to take a look. I'm not familiar with mu detailer, but I'll see if I can check that out as well. I did just push a commit with some better support for dark mode. It's not very pretty, but at least it's usable now!

> I did a bit more testing and it seems like my earlier flagged issue of saves not persisting between rebooting my system in incognito mode is still in V2.0. Hopefully you can find a fix that issue :)

By definition, incognito mode clears things like localstorage/ indexed DB. However, I did add a setting to save to a persistent file instead, have you tried that yet?

> On my regular install it throws some errors and sd doesn't generate anything, on the fresh install that I tried the 1.0 extension (A111 1.7.0 still) same thing, but on a fresh Forge (A1111 fork) install **seems to work well**, so that's a me issue.
> 
> One little thing that annoys me is that the full screen mode is white when I am using dark mode, but other than that, all good.

I'm on 1.7.0 as well, so I'm tempted to take your word for it that it's a problem on your end ;) Please note Forge is not officially supported, and I've never even used it, so all bets are off there. Dark mode is now supported though!

Thanks for the feedback and helping test it everyone!

**Comment by PeanutButterSkeletonCrew** [comment] 2024-03-08 10:32
> > I did a bit more testing and it seems like my earlier flagged issue of saves not persisting between rebooting my system in incognito mode is still in V2.0. Hopefully you can find a fix that issue :)
> 
> By definition, incognito mode clears things like localstorage/ indexed DB. However, I did add a setting to save to a persistent file instead, have you tried that yet?
> 

I wasn't aware of the persistent file option. I tried it and it appears to work, thank you! 

I had a few initial issues with it; it failed to create the history.txt file initially but I have some issues with file permissions on the drive I run SD from so that is possibly the culprit. After manually creating a history.txt file, I had a strange issue where attempting to save a favourite would cause most of the web UI to become unresponsive. I fixed this by saving a favourite as soon as A111 had loaded (essentially a blank favourite). After that, everything behaved as expected. I wonder if this issue was caused by me manually creating a blank text file for the history.txt file after that failed to be created?

However, once I resolved those teething problems, the persistent file option seems to work perfectly. Thanks again for implementing it. State Manager is already saving me plenty of time.

As a note, I switched over to Forge after resolving these issues and State Manager seems to work well there. There are similar issues with ControlNet like I mentioned above (Forge's version of Control Net is slightly different as it's native rather than an extension) but other than that everything seemed to work as expected.

**Comment by SenshiSentou** [comment] 2024-03-08 14:02
Interesting.. Thanks for sharing your findings! I'll try deleting and seeing how it behaves without the file present.

Everyone keeps mentioning Forge! I think I'll have to check that out at some point, though I'll focus on stock A1111 for now :)

Glad you're finding the extension useful!

**Comment by SenshiSentou** [comment] 2024-03-11 20:00
Just pushed a change to 2.0-beta that adds support for ControlNet.

It doesn't get its own pretty accordion, because the internal CN naming is absolutely awful (simply `txt2img/Enable` rather than `txt2img/ControlNet/Enable` for example), and I *really* dislike adding extra code just to handle exception cases like this. CN is a big one though, so I might change my mind on this later. Regardless, it does at least correctly save and load all 3 units separately.

**Closed as completed** 2024-03-20 01:00 UTC
